name: PR Check

on:
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read
  pull-requests: write

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Quick Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libxcb-shape0-dev libxcb-xfixes0-dev

      - name: Download dependencies
        run: cargo fetch --locked

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Run clippy
        run: cargo clippy -- -D warnings

      - name: Run tests
        run: cargo test --locked

      - name: Check build
        run: cargo build --release --locked

  build-test:
    name: Build Test ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libxcb-shape0-dev libxcb-xfixes0-dev

      - name: Download dependencies
        run: cargo fetch --locked

      - name: Build
        run: cargo build --locked

      - name: Verify build
        shell: bash
        run: |
          echo "=== Build completed successfully ==="
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            ls -la target/debug/*.exe || echo "No exe files found"
          else
            ls -la target/debug/SteamCloudFileManager || echo "Binary not found"
          fi
